config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "pages#home"
  get '/about', to: 'pages#about'
  get '/help', to: 'pages#help'
  
  resources :todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
	validates :name, presence: true
	validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end
	def about
	end
	def help
	end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:edit, :update, :show, :destroy]
  
  def new
    @todo = Todo.new
  end
	
	def create
		@todo = Todo.new(todo_params)
		if @todo.save
			flash[:notice] = "Todo added successfuly!"
			redirect_to todo_path(@todo)
		else
			render 'new'
		end
	end
	
	def show
	end
	
	def edit
	  @todo = Todo.find(params[:id])
	end
	
	def update
    if @todo.update(todo_params)
      flash[:notice] = "Todo was successfuly updated"
      redirect_to todo_path(@todo)
    else
      render 'edit'
    end
	end
	
	def index
	  @todos = Todo.all
	end
	
	def destroy
	  @todo.destroy
	  flash[:notice] = "Todo was successfuly deleted"
	  redirect_to todos_path
	end
	
	private
	
	def set_todo
	  @todo = Todo.find(params[:id])
	end
	def todo_params
		params.require(:todo).permit(:name, :description)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <ul>
    <li><%= msg %></li>
  </ul>
<% end %>

app/views/layouts/_navbar.html.erb
<a href="/">Home page</a>
<%= link_to "My todos", todos_path %>
<a href="/about">about page</a>
<a href="/help">help page</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kiruban's Todoapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is the about page</h1>

app/views/pages/help.html.erb
<h1>This is my help page</h1>

app/views/pages/home.html.erb
<h1>Hello World</h1>

<p>test</p>

app/views/todos/_form.html.erb
<% if @todo.errors.any? %>
	<h2>The following errors prevented the todo being saved :</h2>
	<ul style="color:red;">
		<% @todo.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>

<%= form_for @todo do |f| %>

  <p>
  	<%= f.label :name %> <br />
  	<%= f.text_field :name %>
  </p>
  <p>
  	<%= f.label :description %> <br />
  	<%= f.text_area :description, size: "60x12" %>
  </p>
	<%= f.submit %>
<% end %>

<p>
	<%= link_to "Back to todos listing", todos_path %>
</p>

app/views/todos/edit.html.erb
<h1>Edit an existing Todo</h1>

<%= render 'form' %>

app/views/todos/index.html.erb
<h1>Listing all todos</h1>

<p>
  <%= link_to "Create a Todo", new_todo_path %>
</p>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
  </tr>
  <% @todos.each do |todo| %>
  <tr>
    <td><%= todo.name %></td>
    <td><%= todo.description %></td>
    <td><%= link_to "Edit", edit_todo_path(todo) %></td>
    <td><%= link_to "Show", todo_path(todo) %></td>
    <td><%= link_to "Delete", todo_path(todo), method: :delete, data: {confirm: "Are you sure?"} %></td>
  </tr>
  <% end %>
</table>

app/views/todos/new.html.erb
<h1>Add a new Todo</h1>

<%= render 'form' %>

app/views/todos/show.html.erb
<h1><%= @todo.name %></h1>

<p><%= @todo.description %></p>

<p>
	<%= link_to "Edit this todo", edit_todo_path(@todo) %>
	<%= link_to "Back to todos listing", todos_path %>
</p>